version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo pre_build has begun...
      - yarn install
  build:
    commands:
      - yarn build

artifacts:
  files:
    - 'build/**/*'
