version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm install -g yarn forever serve
      - yarn install
  build:
    commands:
      - yarn build

artifacts:
  files:
    - '**/*'
